### ISSUE TITLE
How to use a custom intl_utils source

### ISSUE THREAD

**Issue by evanwsu** [localizely/flutter-intl-intellij#112]
I want to use a custom intl_utils source, what do I do?
When enabled is true, run pub get, which downloads intl_utils from pub.dev to override the locally activated intl_utils.
```
flutter_intl:
enabled: true
```

**Comment by lzoran** [comment]
As far as I remember, the Flutter Intl plugin does not support the use of a custom source for the `intl_utils` package. However, you could consider adding a custom source as a dev dependency to your project. After that, you can invoke it manually or integrate it with a build runner to automate the process (I haven't checked this approach). This method may serve as a workaround for your use case.

The `pubspec.yaml` file:
```
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils:
    git:
      url: https://github.com/localizely/intl_utils # Your source
      
flutter_intl:
  enabled: false # Disable Flutter Intl to prevent overwriting
```

Manually generate localization code:
```
dart run intl_utils:generate
```
