### ISSUE TITLE
Disable auto generation in IDE

### ISSUE THREAD

**Issue by npateras** [localizely/flutter-intl-intellij#119]
Every time there is a change in my pubspec file, the generate command runs, I want to stop that. How is it possible?
My pubspec configuration for intl:
```yaml
flutter_intl:
  enabled: true
  class_name: I10n
  main_locale: en
  arb_dir: assets/locales
  output_dir: lib/app/generated
  use_deferred_loading: true
```

I don't want to set enabled to false as I need this. Disabling it works but will this break the package?
