### ISSUE TITLE
linter

### ISSUE THREAD

**Issue by The28AWG** [localizely/flutter-intl-intellij#52]
Add support ignore for file linter rules in analysis_options.yaml
My linter section:
```yaml
linter:
  rules:
    omit_local_variable_types: false
    unnecessary_this: false
    always_use_package_imports: true
    avoid_print: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_void_to_null: true
```
Generate
```dart
// ignore_for_file: always_use_package_imports
// ignore_for_file: avoid_print
// ignore_for_file: iterable_contains_unrelated_type
// ignore_for_file: list_remove_unrelated_type
// ignore_for_file: literal_only_boolean_expressions
// ignore_for_file: no_duplicate_case_values
// ignore_for_file: no_logic_in_create_state
// ignore_for_file: prefer_void_to_null
```
